artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Abdul-Qadir3/NextJs/raw/main/checken_fecal_images.zip
  local_data_files: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion